[project]
name = "blog_maker"
version = "0.1.0"
description = "blog_maker using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.15"
dependencies = [
    "crewai[tools]>=1.14.0"
]

[project.scripts]
blog_maker = "blog_maker.main:run"
run_crew = "blog_maker.main:run"
train = "blog_maker.main:train"
replay = "blog_maker.main:replay"
test = "blog_maker.main:test"
run_with_trigger = "blog_maker.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
