"""
Disclaimer — Financial disclaimer text for compliance.

Must be included in every generated report per SEBI compliance requirements.
"""

DISCLAIMER = """
---

## ⚠️ Disclaimer

This report is generated by an AI-powered educational tool for **learning and research purposes only**.

- This is **NOT financial, investment, trading, or legal advice**.
- The data and analysis presented may be **delayed, incomplete, or inaccurate**.
- Past performance does not guarantee future results.
- Stock market investments are subject to **market risks**.
- Please consult a **SEBI-registered investment advisor** before making any investment decisions.

> _This application is for educational and research purposes only.
> It does not provide financial, investment, trading, or legal advice.
> Please consult a SEBI-registered investment advisor before making investment decisions._
""".strip()

DISCLAIMER_SHORT = (
    "⚠️ This report is for educational purposes only. "
    "Not financial advice. Consult a SEBI-registered advisor before investing."
)
