"""
Writer Agent — Final Research Report Generation

Responsibilities:
- Reads all findings and critique from shared state
- Generates a comprehensive Markdown research report
- Report includes: title, executive summary, questions, key findings,
  MCP usage explanation, agent flow, limitations, conclusion
- Uses real LLM or structured template based on config
- Sends a validated MCP-style 'final_report_created' message
- Updates shared state with final_report
"""

import logging
import uuid
from datetime import datetime, timezone

from app.config import config
from app.state.research_state import ResearchState
from app.validation.message_validator import create_message

logger = logging.getLogger(__name__)


def _build_template_report(state: ResearchState) -> str:
    """Build a structured Markdown report from state data (no LLM needed)."""
    topic = state["topic"]
    questions = state["research_questions"]
    findings = state["findings"]
    critique = state["critique"]
    messages = state["agent_messages"]
    session_id = state["session_id"]
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Quality summary from messages
    critique_msg = next(
        (m for m in reversed(messages) if m.get("message_type") == "critique_created"),
        None,
    )
    quality = critique_msg["payload"].get("overall_quality", "good") if critique_msg else "good"
    retry_count = state.get("critic_retry_count", 0)

    # ── Title & Header ──────────────────────────────────────────────────────
    report = f"""# Research Report: {topic}

---

**Session ID**: `{session_id}`
**Generated**: {generated_at}
**Quality Assessment**: {quality.title()}
**Agent Iterations**: {retry_count + 1}

---

## Executive Summary

This research report was generated by the **Research Assistant System**, a multi-agent AI application
that demonstrates how AI agents can collaborate using **MCP-style structured messages** and a shared
context store.

The research topic **"{topic}"** was analyzed through a pipeline of six specialized agents:
Planner, Retriever, Embedding, Analyst, Critic, and Writer. Each agent contributed to building
a comprehensive understanding of the topic, with all inter-agent communication validated against
a JSON Schema.

**{len(findings)} key findings** were extracted across **{len(questions)} research questions**,
supported by context retrieved from a local knowledge base and embedding-based semantic search.

---

## Research Questions

The following research questions were generated by the **Planner Agent**:

"""
    for i, q in enumerate(questions, 1):
        priority_badge = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(
            q.get("priority", "medium"), "⚪"
        )
        report += f"{i}. {priority_badge} **[{q.get('priority', 'medium').upper()}]** {q['question']}\n"

    # ── Key Findings ────────────────────────────────────────────────────────
    report += f"""
---

## Key Findings

The following findings were extracted by the **Analyst Agent** using semantic search
over embedded context chunks:

"""
    confidence_emoji = {"high": "✅", "medium": "⚠️", "low": "❌"}

    for i, finding in enumerate(findings, 1):
        emoji = confidence_emoji.get(finding.get("confidence", "low"), "❓")
        chunks_str = ", ".join(f"`{c}`" for c in finding.get("supporting_chunks", []))

        report += f"""### Finding {i}: {finding['question']}

{emoji} **Confidence**: {finding.get('confidence', 'unknown').title()}

{finding['insight']}

**Supporting Context**: {chunks_str if chunks_str else 'N/A'}

"""

    # ── MCP Usage ───────────────────────────────────────────────────────────
    msg_types = [m["message_type"] for m in messages]
    msg_type_counts: dict[str, int] = {}
    for mt in msg_types:
        msg_type_counts[mt] = msg_type_counts.get(mt, 0) + 1

    report += """---

## MCP Usage in This Research Session

This project implements **MCP-style (Model Context Protocol)** structured messaging
between all agents. Key MCP concepts demonstrated:

### 1. Structured Agent Messages
Every agent communicates via a standardized message format validated against a JSON Schema:

```json
{
  "message_id": "msg_001",
  "session_id": "research_001",
  "sender_agent": "planner_agent",
  "receiver_agent": "retriever_agent",
  "message_type": "research_plan_created",
  "timestamp": "2026-05-28T10:00:00Z",
  "payload": { ... },
  "metadata": { ... }
}
```

### 2. Shared Context Store
All agents read from and write to a shared `ResearchState` object — acting as the
MCP-style context layer that enables agents to build on each other's work.

### 3. MCP Tools Used
- `save_context` — Stores retrieved context chunks
- `get_context` — Reads shared context
- `save_embedding` — Stores embedding vectors
- `search_context` — Semantic search over context
- `log_agent_message` — Logs agent communication

### 4. MCP Resources Exposed
- `research://session/{id}` — Current session data
- `research://context/{id}` — Retrieved context
- `research://embeddings/{id}` — Embedding records
- `research://messages/{id}` — Agent message log

"""

    # ── Message types sent ──────────────────────────────────────────────────
    report += "### 5. Messages Exchanged This Session\n\n"
    report += "| Message Type | Count |\n|---|---|\n"
    for msg_type, count in msg_type_counts.items():
        report += f"| `{msg_type}` | {count} |\n"
    report += "\n"

    # ── Agent Collaboration Flow ─────────────────────────────────────────────
    report += """---

## Agent Collaboration Flow

```
User CLI Input (Research Topic)
         │
         ▼
┌─────────────────────┐
│   Planner Agent     │ → Generates research questions
│   [planner_agent]   │ → Sends: research_plan_created
└──────────┬──────────┘
           │
           ▼
┌─────────────────────┐
│  Retriever Agent    │ → Searches knowledge base
│  [retriever_agent]  │ → Sends: context_retrieved
└──────────┬──────────┘
           │
           ▼
┌─────────────────────┐
│  Embedding Agent    │ → Creates vector embeddings
│  [embedding_agent]  │ → Sends: embeddings_created
└──────────┬──────────┘
           │
           ▼
┌─────────────────────┐
│   Analyst Agent     │ → Extracts insights via semantic search
│   [analyst_agent]   │ → Sends: findings_created
└──────────┬──────────┘
           │
           ▼
┌─────────────────────┐
│    Critic Agent     │ → Reviews finding quality
│    [critic_agent]   │ → Sends: critique_created
└──────────┬──────────┘
           │
     ┌─────┴──────┐
     │            │
  needs_         approved
  improvement       │
     │              ▼
     │    ┌─────────────────────┐
     │    │    Writer Agent     │ → Generates final report
     │    │   [writer_agent]    │ → Sends: final_report_created
     │    └─────────────────────┘
     │
     └──→ Retriever Agent (retry loop, max {max_retries} retries)
```

""".format(max_retries=config.MAX_CRITIC_RETRIES)

    # ── Critique & Limitations ───────────────────────────────────────────────
    report += "---\n\n## Limitations & Critic Feedback\n\n"

    if critique:
        report += "The **Critic Agent** identified the following areas for improvement:\n\n"
        for issue in critique:
            report += f"- ⚠️ {issue}\n"
        report += "\n"
    else:
        report += "✅ The **Critic Agent** approved the findings without major issues.\n\n"

    report += """### General Limitations of This Demo

- Knowledge base is limited to local markdown files
- Context retrieval uses simple keyword matching and semantic embeddings
- LLM responses in mock mode are template-based, not truly AI-generated
- This is an educational demo, not a production research tool

---

## Conclusion

This Research Assistant System demonstrates how multiple AI agents can collaborate on a
complex research task using:

1. **MCP-style structured messages** for agent-to-agent communication
2. **JSON Schema validation** to ensure message integrity
3. **Shared context store** (ResearchState) accessible by all agents
4. **Semantic embeddings** for intelligent context retrieval
5. **LangGraph** for stateful workflow orchestration with conditional routing
6. **CrewAI** for role-based agent definition

The **Critic → Retriever feedback loop** demonstrates how agents can self-correct,
requesting additional context when findings are insufficient.

---

*Generated by Research Assistant System | MCP Multi-Agent Demo*
"""
    return report


def _llm_report(state: ResearchState) -> str:
    """Generate report using OpenAI LLM for the narrative sections."""
    try:
        from openai import OpenAI

        client = OpenAI(api_key=config.OPENAI_API_KEY)
        topic = state["topic"]
        findings_text = "\n".join(
            f"Q: {f['question']}\nInsight: {f['insight']}\nConfidence: {f['confidence']}"
            for f in state["findings"]
        )

        prompt = f"""You are a research writer. Write a comprehensive research report on:

Topic: {topic}

Findings:
{findings_text}

Write a structured Markdown report with:
1. Executive Summary (2-3 paragraphs)
2. Key Findings (for each finding, provide a heading and detailed explanation)
3. Limitations
4. Conclusion

Use clear, professional language. Use Markdown formatting."""

        response = client.chat.completions.create(
            model=config.OPENAI_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5,
            max_tokens=2000,
        )

        llm_content = response.choices[0].message.content

        # Wrap with session metadata
        header = f"# Research Report: {topic}\n\n"
        header += f"*Generated by Research Assistant System*\n\n---\n\n"
        return header + llm_content + "\n\n---\n\n*Multi-Agent MCP Demo*\n"

    except Exception as e:
        logger.warning(f"LLM writer failed, using template: {e}")
        return _build_template_report(state)


# ─────────────────────────────────────────────
# LangGraph node function
# ─────────────────────────────────────────────

def writer_node(state: ResearchState) -> dict:
    """
    LangGraph node for the Writer Agent.

    Reads: state['findings'], state['critique'], state['research_questions'], state['agent_messages']
    Writes: state['final_report'], state['agent_messages']
    """
    session_id = state["session_id"]
    findings = state["findings"]

    logger.info(
        f"[Writer Agent] Generating final report from {len(findings)} findings"
    )

    # Generate report
    if config.USE_MOCK_LLM:
        final_report = _build_template_report(state)
    else:
        final_report = _llm_report(state)

    word_count = len(final_report.split())
    logger.info(f"[Writer Agent] ✓ Report generated ({word_count} words)")

    # Create MCP-style message
    message = create_message(
        message_id=f"msg_{uuid.uuid4().hex[:8]}",
        session_id=session_id,
        sender_agent="writer_agent",
        receiver_agent="system",
        message_type="final_report_created",
        payload={
            "report_length_words": word_count,
            "finding_count": len(findings),
            "section_count": 8,
        },
        metadata={
            "priority": "high",
            "requires_response": False,
        },
    )

    return {
        "final_report": final_report,
        "agent_messages": state["agent_messages"] + [message],
    }
