"""
Weather MCP Client — Connects to the WeatherMCP server via stdio transport.
Demonstrates: discovery, manual calls, resources reading, and LangChain tool conversion.
"""

import asyncio
import os
import sys
import json
from dotenv import load_dotenv
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

# Load environment variables
load_dotenv()

class WeatherMCPClient:
    """A clean, premium client to interact with the WeatherMCP Server."""
    
    def __init__(self, server_path: str):
        self.server_path = server_path
        # Setup parameters to launch our server script as a subprocess
        self.server_params = StdioServerParameters(
            command=sys.executable,
            args=[self.server_path],
            env=None
        )
        self._connection = None
        self._session = None

    async def run_interaction_demo(self):
        """Connect to the server and execute a full demonstration of tools, resources, and prompts."""
        print("📡 Connecting to WeatherMCP Server via stdio transport...", flush=True)
        
        async with stdio_client(self.server_params) as (read, write):
            async with ClientSession(read, write) as session:
                print("session", session, flush=True)
                # 1. Perform initialization handshake
                await session.initialize()
                print("✅ Handshake complete. Connected to WeatherServer!\n")

                # 2. Discover available tools
                print("━━━ 1. DISCOVERING TOOLS ━━━━━━━━━━━━━━━━━━━━━━━━")
                tools_result = await session.list_tools()
                print(f"📦 Server exposes {len(tools_result.tools)} tool(s):\n")
                for tool in tools_result.tools:
                    print(f"  🔧 Tool Name   : {tool.name}")
                    print(f"     Description : {tool.description}")
                    print(f"     Schema      : {json.dumps(tool.inputSchema.get('properties'), indent=6)}")
                    print()

                # 3. Call the weather tool
                print("━━━ 2. INVOKING TOOLS (LIVE FORECAST API) ━━━━━━━━")
                cities = ["mumbai", "bangalore", "london"]
                for city in cities:
                    print(f"🔍 Querying forecast for '{city.title()}'...")
                    result = await session.call_tool(
                        "get_weather",
                        arguments={"city": city}
                    )
                    # Extract text content
                    raw_json = result.content[0].text
                    weather = json.loads(raw_json)
                    print(f"   🌡️ Temperature : {weather['temperature_celsius']}°C")
                    print(f"   💨 Windspeed   : {weather['windspeed_kmh']} km/h")
                    print(f"   📡 DataSource  : {weather['source']}")
                    print()

                # 4. Read resources (Weather Alerts)
                print("━━━ 3. READING READ-ONLY RESOURCES ━━━━━━━━━━━━━━")
                target_cities = ["mumbai", "bangalore", "tokyo"]
                for city in target_cities:
                    uri = f"weather://alerts/{city}"
                    print(f"📂 Reading resource '{uri}'...")
                    resource_result = await session.read_resource(uri)
                    print(resource_result.contents[0].text)
                    print()

                # 5. Fetch Prompts (Weather Adviser)
                print("━━━ 4. RENDERING PROMPTS ━━━━━━━━━━━━━━━━━━━━━━━━")
                print("📋 Requesting 'weather_adviser' prompt for Bangalore travel plans...")
                prompt_result = await session.get_prompt(
                    "weather_adviser",
                    arguments={"city": "bangalore", "travel_plan": "outdoor historical walks and dining"}
                )
                
                print("   Messages generated by MCP Server for LLM consumption:")
                for i, msg in enumerate(prompt_result.messages):
                    print(f"     [{msg.role.upper()}]:")
                    lines = msg.content.text.split("\n")
                    # print first 5 lines for brevity
                    for line in lines[:6]:
                        print(f"       {line}")
                    if len(lines) > 6:
                        print("       ...")
                print()

                # 6. LangChain tool loading demonstration & LLM Agent execution
                print("━━━ 5. LANGCHAIN TOOL ADAPTER & LLM AGENT RUN ━━━━")
                try:
                    from langchain_mcp_adapters.tools import load_mcp_tools
                    lc_tools = await load_mcp_tools(session)
                    print(f"   ✔ Success! Successfully loaded {len(lc_tools)} MCP tools into LangChain:")
                    for tool in lc_tools:
                        print(f"     - LangChain Tool: {tool.name} (args: {list(tool.args.keys())})")
                    print()

                    # Check for OpenAI API key in environment to execute a live LLM run
                    openai_key = os.getenv("OPENAI_API_KEY")
                    if openai_key and len(openai_key.strip()) > 10:
                        print("📡 OPENAI_API_KEY found! Invoking live LangGraph React Agent...")
                        from langchain_openai import ChatOpenAI
                        from langgraph.prebuilt import create_react_agent
                        
                        llm = ChatOpenAI(model="gpt-4o-mini", api_key=openai_key)
                        
                        # Create dynamic React Agent with our loaded MCP tools
                        agent = create_react_agent(
                            llm, 
                            tools=lc_tools,
                            prompt="You are an expert travel weather advisory assistant. Analyze weather inputs and help the traveler."
                        )
                        
                        # Invoke LLM Agent to dynamically decide to call our MCP weather tool!
                        print("🤖 Question: 'Should I wear a winter jacket in London today? Please call the weather tool to check.'")
                        agent_response = await agent.ainvoke({
                            "messages": [("user", "Should I wear a winter jacket in London today? Please call the weather tool to check.")]
                        })
                        
                        final_response = agent_response["messages"][-1].content
                        print(f"\n🤖 Agent Response:\n{final_response}\n")
                    else:
                        print("ℹ️ OPENAI_API_KEY not found in .env. Skipping live LangChain agent execution.")
                        print("   (Add OPENAI_API_KEY=your-key to projects/weather-mcp-assistant/.env to enable live agent runs!)")
                except Exception as e:
                    print(f"   ℹ️ LangChain loading or run skipped: {str(e)}")
                print()

async def run_client_demo(server_script: str):
    client = WeatherMCPClient(server_script)
    await client.run_interaction_demo()

if __name__ == "__main__":
    # Test path resolution when run standalone
    current_dir = os.path.dirname(os.path.abspath(__file__))
    server_path = os.path.join(current_dir, "weather_server.py")
    if os.path.exists(server_path):
        asyncio.run(run_client_demo(server_path))
    else:
        print(f"❌ Server file not found at {server_path}. Run via main.py or specify path.", file=sys.stderr)
